### ISSUE TITLE
Authenticate spitting our error when no token found

### ISSUE THREAD

**Issue by colescott** [Team4159/birds#23]
This should be changed to a custom output

Attempting to access protected call without auth header set results in error:

`UnauthorizedError: No authorization token was found
<br> &nbsp; &nbsp;at middleware (/home/cole/BIRDS/node_modules/express-jwt/lib/index.js:72:21)
<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/cole/BIRDS/node_modules/express/lib/router/layer.js:95:5)
<br> &nbsp; &nbsp;at next (/home/cole/BIRDS/node_modules/express/lib/router/route.js:131:13)
<br> &nbsp; &nbsp;at Route.dispatch (/home/cole/BIRDS/node_modules/express/lib/router/route.js:112:3)
<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/cole/BIRDS/node_modules/express/lib/router/layer.js:95:5)
<br> &nbsp; &nbsp;at /home/cole/BIRDS/node_modules/express/lib/router/index.js:277:22
<br> &nbsp; &nbsp;at param (/home/cole/BIRDS/node_modules/express/lib/router/index.js:349:14)
<br> &nbsp; &nbsp;at param (/home/cole/BIRDS/node_modules/express/lib/router/index.js:365:14)
<br> &nbsp; &nbsp;at Function.process_params (/home/cole/BIRDS/node_modules/express/lib/router/index.js:410:3)
<br> &nbsp; &nbsp;at next (/home/cole/BIRDS/node_modules/express/lib/router/index.js:271:10)
<br> &nbsp; &nbsp;at initialize (/home/cole/BIRDS/node_modules/passport/lib/middleware/initialize.js:62:5)
<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/cole/BIRDS/node_modules/express/lib/router/layer.js:95:5)
<br> &nbsp; &nbsp;at trim_prefix (/home/cole/BIRDS/node_modules/express/lib/router/index.js:312:13)
<br> &nbsp; &nbsp;at /home/cole/BIRDS/node_modules/express/lib/router/index.js:280:7
<br> &nbsp; &nbsp;at Function.process_params (/home/cole/BIRDS/node_modules/express/lib/router/index.js:330:12)
<br> &nbsp; &nbsp;at next (/home/cole/BIRDS/node_modules/express/lib/router/index.js:271:10)
`

**Comment by colescott** [comment]
Fixed in #24
